In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.power as smp
import statsmodels.stats.proportion as smprop


In [4]:
# Path to file 
file_path = 'data.csv'

# Load data
D = pd.read_csv(file_path,sep=',')
D

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
d_test = D[1:]

observed = np.array([d_test['right-right'], d_test['right-wrong']])

observed

array([[ 5, 17,  8, 14],
       [15,  4, 10,  8]], dtype=int64)

In [ ]:
chi2, p, dof, expected = stats.chi2_contingency(observed)
chi2, p, dof, expected

(14.408877516832066,
 0.0023982711915381807,
 3,
 array([[10.86419753, 11.40740741,  9.77777778, 11.95061728],
        [ 9.13580247,  9.59259259,  8.22222222, 10.04938272]]))

### Pairwise

In [ ]:
observed[:,[0,1]]

array([[ 5, 17],
       [15,  4]], dtype=int64)

In [ ]:

subject_dict = {0: "Mathematics", 1: "Statistics", 2:"Machine", 3:"Social Science"}
pvals = []
for i in range(4):
    for j in range(i,4):
        if i != j:
            #chi2, p, dof, expected = stats.chi2_contingency(observed[:,[i,j]])
            statistic, p = stats.fisher_exact(observed[:,[i,j]])
            print("____________________________")
            print(f"Difference between {subject_dict[i]} and {subject_dict[j]}")
            #print(expected)
            print(f'p-val: {p}')
            pvals.append(p)


NameError: name 'stats' is not defined

In [ ]:
q = 0.05
m = 6
for i, p in enumerate(sorted(pvals)):
    significance = (i+1)/m * q

    if significance > p:
        print("reject ---", round(significance,3), ">", round(p,6))
    else:
        print("accept ---", round(significance,3), "<", round(p,6))

reject --- 0.008 > 0.000506
reject --- 0.017 > 0.015704
reject --- 0.025 > 0.02367
accept --- 0.033 < 0.307124
accept --- 0.042 < 0.310155
accept --- 0.05 < 0.339125


In [ ]:
m = 4
bonf_alpha = 0.05/ ((m* (m-1))/ 2)   # alpha of 5% with M = 3 tests 
n = 25

print(bonf_alpha)

n_obs = np.array([n,n])

for i in range(m-1):
    for k in range(i+1,m):
        z_obs, p_val = smprop.proportions_ztest(count =(observed[1,i],observed[1,k]), nobs = n_obs)
        if p_val < bonf_alpha: 
            print(f'reject, {i+1} and {k+1}, pval {p_val}')
        else: 
            print(f'accept, {i+1} and {k+1}, pval {p_val}')

# Math : 1, Stat: 2, Machine: 3, Social Science: 4


0.008333333333333333
reject, 1 and 2, pval 0.001350901652264132
accept, 1 and 3, pval 0.15729920705028533
accept, 1 and 4, pval 0.04700388031557925
accept, 2 and 3, pval 0.05878172135535886
accept, 2 and 4, pval 0.18532630419857943
accept, 3 and 4, pval 0.5556897902827945
