In [63]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.power as smp
import statsmodels.stats.proportion as smprop


In [64]:
# Path to file 
file_path = 'data.csv'

# Load data
D = pd.read_csv(file_path,sep=',')
D

category       subcategory  right-right  wrong-wrong  right-wrong  \
0  Short_question            trivia           25            0            0   
1   Computational        mathmatics            5            5           15   
2   Computational        statistics           17            3            4   
3   Computational    social_science            9            1            3   
4   Computational  machine_Learning            8            6           10   

   wrong-right  
0            0  
1            0  
2            1  
3            0  
4            1

In [65]:

observed_normal = np.array([D['right-right'] + D['right-wrong'], D['wrong-wrong']+ D['wrong-right']])
observed_nudge = np.array([D['right-right'] +D['wrong-right'], D['wrong-wrong']+  D['right-wrong']])
observed_normal

array([[25, 20, 21, 12, 18],
       [ 0,  5,  4,  1,  7]], dtype=int64)

In [66]:
chi2, p, dof, expected = stats.chi2_contingency(observed_normal)
chi2, p, dof, expected

(8.758352187028658,
 0.06743164414537377,
 4,
 array([[21.23893805, 21.23893805, 21.23893805, 11.04424779, 21.23893805],
        [ 3.76106195,  3.76106195,  3.76106195,  1.95575221,  3.76106195]]))

In [67]:
chi2n, pn, dofn, expectedn = stats.chi2_contingency(observed_nudge)
chi2n, pn, dofn, expectedn

(40.67843078906909,
 3.1330652164357776e-08,
 4,
 array([[14.60176991, 14.60176991, 14.60176991,  7.59292035, 14.60176991],
        [10.39823009, 10.39823009, 10.39823009,  5.40707965, 10.39823009]]))