In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.power as smp
import statsmodels.stats.proportion as smprop


In [4]:
# Path to file 
file_path = 'data.csv'

# Load data
D = pd.read_csv(file_path,sep=',')
D

category       subcategory  right-right  wrong-wrong  right-wrong  \
0  Short_question            trivia           25            0            0   
1   Computational        mathmatics            5            5           15   
2   Computational        statistics           17            3            4   
3   Computational  machine_Learning            8            6           10   
4   Computational    Social_science           14            3            8   

   wrong-right  
0            0  
1            0  
2            1  
3            1  
4            0

In [5]:
d_test = D[1:]

observed = np.array([d_test['right-right'], d_test['right-wrong']])

observed

array([[ 5, 17,  8, 14],
       [15,  4, 10,  8]], dtype=int64)

In [6]:
chi2, p, dof, expected = stats.chi2_contingency(observed)
chi2, p, dof, expected

(14.408877516832066,
 0.0023982711915381807,
 3,
 array([[10.86419753, 11.40740741,  9.77777778, 11.95061728],
        [ 9.13580247,  9.59259259,  8.22222222, 10.04938272]]))

### Pairwise

In [14]:
observed[:,[0,1]]

array([[ 5, 17],
       [15,  4]], dtype=int64)

In [33]:
m = 4
bonf_alpha = 0.05/ ((m* (m-1))/ 2)   # alpha of 5% with M = 3 tests 

print("alpha bonferoni: ", bonf_alpha)
subject_dict = {0: "Mathematics", 1: "Statistics", 2:"Machine", 3:"Social Science"}
for i in range(4):
    for j in range(i,4):
        if i != j:
            #chi2, p, dof, expected = stats.chi2_contingency(observed[:,[i,j]])
            statistic, p = stats.fisher_exact(observed[:,[i,j]])
            print("____________________________")
            print(f"Difference between {subject_dict[i]} and {subject_dict[j]}")
            #print(expected)
            if p < bonf_alpha: 
                print(f'reject, pval: {p}')
            else: 
                print(f'accept, pval: {p}')
# Math : 1, Stat: 2, Machine: 3, Social Science: 4

alpha bonferoni:  0.008333333333333333
____________________________
Difference between Mathematics and Statistics
reject, pval: 0.0005061684314111601
____________________________
Difference between Mathematics and Machine
accept, pval: 0.3071237453884839
____________________________
Difference between Mathematics and Social Science
accept, pval: 0.01570376909914065
____________________________
Difference between Statistics and Machine
accept, pval: 0.023669943580955817
____________________________
Difference between Statistics and Social Science
accept, pval: 0.3101545631324417
____________________________
Difference between Machine and Social Science
accept, pval: 0.3391251453610597


In [ ]:

m = 4
bonf_alpha = 0.05/ ((m* (m-1))/ 2)   # alpha of 5% with M = 3 tests 
n = 25

print(bonf_alpha)

n_obs = np.array([n,n])

for i in range(m-1):
    for k in range(i+1,m):
        z_obs, p_val = smprop.proportions_ztest(count =(observed[1,i],observed[1,k]), nobs = n_obs)
        if p_val < bonf_alpha: 
            print(f'reject, {i+1} and {k+1}, pval {p_val}')
        else: 
            print(f'accept, {i+1} and {k+1}, pval {p_val}')

# Math : 1, Stat: 2, Machine: 3, Social Science: 4


0.008333333333333333
reject, 1 and 2, pval 0.001350901652264132
accept, 1 and 3, pval 0.15729920705028533
accept, 1 and 4, pval 0.04700388031557925
accept, 2 and 3, pval 0.05878172135535886
accept, 2 and 4, pval 0.18532630419857943
accept, 3 and 4, pval 0.5556897902827945
