In [15]:
#Husk at impotere!
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.power as smp
import statsmodels.stats.proportion as smprop
# evt import math


# Neutral

In [16]:
#Reading the data into Python
table_data_neutral = np.array([[20,5],[21,4],[18,7],[22,3]])
table_data_neutral

array([[20,  5],
       [21,  4],
       [18,  7],
       [22,  3]])

In [17]:
#Sætter bare kolonne/rækkenavne på tabellen:
table_data_neutral = pd.DataFrame(table_data_neutral, index=["Math2", "Stats","ML", "Social"],
columns=["Correct", "Incorrect"])
print(table_data_neutral)

        Correct  Incorrect
Math2        20          5
Stats        21          4
ML           18          7
Social       22          3


In [18]:
# Chi^2 test for testing that the distribution for the two groups are equal
chi2, p_val, dof, expected = stats.chi2_contingency(table_data_neutral, correction=False)

# Tabel med de forventede værdier, hvis nulhypotesen var sand
print(expected)

print()
# Test Statistic
print("chi_2_obs =",chi2)

# P value
print("p_val =", p_val)

# Degrees of freedom
print("df =", dof)

[[20.25  4.75]
 [20.25  4.75]
 [20.25  4.75]
 [20.25  4.75]]

chi_2_obs = 2.2742040285899936
p_val = 0.5174807351498061
df = 3


# Biased

In [19]:
#Reading the data into Python
table_data_biased = np.array([[5,20],[18,7],[9,16],[14,11]])
table_data_biased

array([[ 5, 20],
       [18,  7],
       [ 9, 16],
       [14, 11]])

In [20]:
#Sætter bare kolonne/rækkenavne på tabellen:
table_data_biased = pd.DataFrame(table_data_biased, index=["Math2", "Stats","ML", "Social"],
columns=["Correct", "Incorrect"])
print(table_data_biased)

        Correct  Incorrect
Math2         5         20
Stats        18          7
ML            9         16
Social       14         11


In [21]:
# Chi^2 test for testing that the distribution for the two groups are equal
chi2, p_val, dof, expected = stats.chi2_contingency(table_data_biased, correction=False)

# Tabel med de forventede værdier, hvis nulhypotesen var sand
print(expected)

print()
# Test Statistic
print("chi_2_obs =",chi2)

# P value
print("p_val =", p_val)

# Degrees of freedom
print("df =", dof)

[[11.5 13.5]
 [11.5 13.5]
 [11.5 13.5]
 [11.5 13.5]]

chi_2_obs = 15.619967793880837
p_val = 0.0013566584057098873
df = 3


## Pairwise comparisons

In [22]:
alpha = 0.05
n = 4
M = n*(n-1)/2
alpha_bonf = alpha/M
alpha_bonf

0.008333333333333333

In [33]:
def pairwise_compare(x1,n1, x2,n2):
    count = np.array([x1,x2])
    nobs = np.array([n1,n2])
    z_obs, p_val = smprop.proportions_ztest(count=count, nobs=nobs)

    # Kan også indsætte data direkte i funktionen:
    # z_obs,p_value = smprop.proportions_ztest(count = [x1, x2], nobs = [n1, n2], value=nulhypotese, prop_var=0)
    # print(z_obs, p_value)
    
    print(f"{z_obs=}")

    print(f"{p_val=}")

    if p_val < alpha_bonf:
        print("Idet pval < alpha, kan vi forkaste nulhypotesen")
    else:
        print("Idet pval > alpha, kan vi acceptere nulhypotesen")

In [ ]:
# Mat
xmat = 20
nmat = 25

# Stat
xstat = 7
nstat = 25

# ML
xML = 16
nML = 25

#Social
xsoc = 14
nsoc = 25



z_obs=3.688778299954577
p_val=0.00022533345908647202
Idet pval < alpha, kan vi forkaste nulhypotesen


Mat vs stat

In [39]:
pairwise_compare(xmat,nmat,xstat,nstat)

z_obs=3.688778299954577
p_val=0.00022533345908647202
Idet pval < alpha, kan vi forkaste nulhypotesen


Mat vs. ML

In [35]:
# Testing that the probabilities (error rates) for the two groups are equal
pairwise_compare(xmat,nmat,xML,nML)

z_obs=1.2598815766974243
p_val=0.20771208572755662
Idet pval > alpha, kan vi acceptere nulhypotesen


Stat vs. ML:

In [36]:
# Testing that the probabilities (error rates) for the two groups are equal
pairwise_compare(xstat,nstat,xML,nML)

z_obs=-2.5537695922762453
p_val=0.010656374721291446
Idet pval > alpha, kan vi acceptere nulhypotesen


In [40]:
pairwise_compare(xstat,nstat,xsoc,nsoc)

z_obs=-2.005738892714385
p_val=0.044884113345636724
Idet pval > alpha, kan vi acceptere nulhypotesen


In [41]:
pairwise_compare(xML,nML,xsoc,nsoc)

z_obs=0.5773502691896255
p_val=0.5637028616507732
Idet pval > alpha, kan vi acceptere nulhypotesen


In [42]:
pairwise_compare(xmat,nmat,xsoc,nsoc)

z_obs=1.8190171877724974
p_val=0.06890880788626995
Idet pval > alpha, kan vi acceptere nulhypotesen
