In [1]:
#Husk at impotere!
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.power as smp
import statsmodels.stats.proportion as smprop
# evt import math


# Neutral

In [27]:
#Reading the data into Python
table_data_neutral = np.array([[20,5],[21,4],[18,7]])
table_data_neutral

array([[20,  5],
       [21,  4],
       [18,  7]])

In [28]:
#Sætter bare kolonne/rækkenavne på tabellen:
table_data_neutral = pd.DataFrame(table_data_neutral, index=["Math2", "Stats","ML"],
columns=["Correct", "Incorrect"])
print(table_data_neutral)

       Correct  Incorrect
Math2       20          5
Stats       21          4
ML          18          7


In [29]:
# Chi^2 test for testing that the distribution for the two groups are equal
chi2, p_val, dof, expected = stats.chi2_contingency(table_data_neutral, correction=False)

# Tabel med de forventede værdier, hvis nulhypotesen var sand
print(expected)

print()
# Test Statistic
print("chi_2_obs =",chi2)

# P value
print("p_val =", p_val)

# Degrees of freedom
print("df =", dof)

[[19.66666667  5.33333333]
 [19.66666667  5.33333333]
 [19.66666667  5.33333333]]

chi_2_obs = 1.1122881355932204
p_val = 0.5734158591652831
df = 2


# Biased

In [32]:
#Reading the data into Python
table_data_biased = np.array([[5,20],[18,7],[9,16]])
table_data_biased

array([[ 5, 20],
       [18,  7],
       [ 9, 16]])

In [33]:
#Sætter bare kolonne/rækkenavne på tabellen:
table_data_biased = pd.DataFrame(table_data_biased, index=["Math2", "Stats","ML"],
columns=["Correct", "Incorrect"])
print(table_data_biased)

       Correct  Incorrect
Math2        5         20
Stats       18          7
ML           9         16


In [34]:
# Chi^2 test for testing that the distribution for the two groups are equal
chi2, p_val, dof, expected = stats.chi2_contingency(table_data_biased, correction=False)

# Tabel med de forventede værdier, hvis nulhypotesen var sand
print(expected)

print()
# Test Statistic
print("chi_2_obs =",chi2)

# P value
print("p_val =", p_val)

# Degrees of freedom
print("df =", dof)

[[10.66666667 14.33333333]
 [10.66666667 14.33333333]
 [10.66666667 14.33333333]]

chi_2_obs = 14.498546511627907
p_val = 0.000710690691537986
df = 2


## Pairwise comparisons

In [9]:
alpha_bonf = 0.05/3
alpha_bonf

0.016666666666666666

Mat vs stat

In [17]:
# Testing that the probabilities (error rates) for the two groups are equal
# Mat
x1 = 20
n1 = 25

# Stat
x2 = 7
n2 = 25

count = np.array([x1,x2])
nobs = np.array([n1,n2])
z_obs, p_val = smprop.proportions_ztest(count=count, nobs=nobs)

# Kan også indsætte data direkte i funktionen:
# z_obs,p_value = smprop.proportions_ztest(count = [x1, x2], nobs = [n1, n2], value=nulhypotese, prop_var=0)
# print(z_obs, p_value)

print(f"{z_obs=}")

print(f"{p_val=}")

if p_val < alpha_bonf:
    print("Idet pval < alpha, kan vi forkaste nulhypotesen")
else:
    print("Idet pval > alpha, kan vi acceptere nulhypotesen")

z_obs=3.688778299954577
p_val=0.00022533345908647202
Idet pval < alpha, kan vi forkaste nulhypotesen


Mat vs. ML

In [ ]:
# Testing that the probabilities (error rates) for the two groups are equal
# Mat
x1 = 20
n1 = 25

# ML
x2 = 16
n2 = 25

count = np.array([x1,x2])
nobs = np.array([n1,n2])
z_obs, p_val = smprop.proportions_ztest(count=count, nobs=nobs)

# Kan også indsætte data direkte i funktionen:
# z_obs,p_value = smprop.proportions_ztest(count = [x1, x2], nobs = [n1, n2], value=nulhypotese, prop_var=0)
# print(z_obs, p_value)

print(f"{z_obs=}")

print(f"{p_val=}")

if p_val < alpha_bonf:
    print("Idet pval < alpha, kan vi forkaste nulhypotesen")
else:
    print("Idet pval > alpha, kan vi acceptere nulhypotesen")

z_obs=1.2598815766974243
p_val=0.20771208572755662
Idet pval > alpha, kan vi acceptere nulhypotesen


Stat vs. ML:

In [18]:
# Testing that the probabilities (error rates) for the two groups are equal
# Stat
x1 = 7
n1 = 25

# ML
x2 = 16
n2 = 25

count = np.array([x1,x2])
nobs = np.array([n1,n2])
z_obs, p_val = smprop.proportions_ztest(count=count, nobs=nobs)

# Kan også indsætte data direkte i funktionen:
# z_obs,p_value = smprop.proportions_ztest(count = [x1, x2], nobs = [n1, n2], value=nulhypotese, prop_var=0)
# print(z_obs, p_value)

print(f"{z_obs=}")

print(f"{p_val=}")

if p_val < alpha_bonf:
    print("Idet pval < alpha, kan vi forkaste nulhypotesen")
else:
    print("Idet pval > alpha, kan vi acceptere nulhypotesen")

z_obs=-2.5537695922762453
p_val=0.010656374721291446
Idet pval < alpha, kan vi forkaste nulhypotesen
